Set up very basic Docsy website
kubereboot/website pull request #1
Opened 2022-09-19 13:15 UTC by dholbach

Based on https://github.com/weaveworks/kured/#readme

To test locally, use the [extended build of Hugo](https://gohugo.io/getting-started/installing/) and run `hugo server` in the branch.

As soon as we can, we will get this hooked up to a Netlify instance through CNCF. 

Signed-off-by: Daniel Holbach <daniel@weave.works>

2022-09-20 09:12 UTC, evrardjp requested changes
few nits in my comments.
In addition to that, maybe we should mention how to contribute  to the website,helm charts, and kured?

2022-09-20 09:12 UTC, evrardjp commented on README.md
> +In order to run the Flux site locally, you need to install the [Hugo](https://gohugo.io) static site generator. Make sure to [install](https://gohugo.io/getting-started/installing/) the "extended" va
Flux is mentioned here.

2022-09-20 09:17 UTC, dholbach commented on README.md
> +In order to run the Flux site locally, you need to install the [Hugo](https://gohugo.io) static site generator. Make sure to [install](https://gohugo.io/getting-started/installing/) the "extended" va
oops :-)

2022-09-20 11:20 UTC, dholbach commented
> few nits in my comments. In addition to that, maybe we should mention how to contribute to the website,helm charts, and kured (the organisation's structure)?

Can we extend the docs in a follow-up PR?

2022-10-02 00:12 UTC, dholbach commented
→ https://deploy-preview-1--kured.netlify.app/

2022-10-02 07:12 UTC, ckotzbauer reviewed
Only two small comments.
The website looks pretty good, it's a good starting point we can improve and extend later.

2022-10-02 07:12 UTC, ckotzbauer commented on content/docs/community.md
> +- [File an issue](https://github.com/weaveworks/kured/issues/new).
Wrong issue link

2022-10-02 07:12 UTC, ckotzbauer commented on netlify.toml
> +  GO_VERSION = "1.18"
Any reason this differs from the version in go.mod?

2022-10-02 08:37 UTC, ckotzbauer approved these changes

2022-10-02 08:38 UTC, merged